### ISSUE TITLE
Add support for nvmes

### ISSUE THREAD

**Issue by Roxedus** [hotio/docker-hddtemp2influxdb#1]
The script expects info that's not on the smart-readout for nvmes. [Pastebin example](https://pastebin.com/8SVpQRrs)

Could you option to use a slimed-down version of the script that doesn't need all the data?

**Comment by hotio** [comment]
should be done with dfada292862987d34ccc4367ad181154648ea0ea and a6f653b1f38eae59dda9c704fe43dbc39ca488d1
